server:
  port: 10010
spring:
  application:
    name: gift-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jarvis_smith/gift-config-server.git
          username: jarvis_smith
          password: 426218107liuf
          search-paths: src/main/resources # 如果不是在根路径下面需要加搜索地址